version: "3.9"

name: ${COMPOSE_PROJECT_NAME:-voiceai}
services:
  backend:
    build:
      context: ./backend/Takeaway.Api
      dockerfile: Dockerfile
    container_name: voiceai-backend
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"
    volumes:
      - ./data:/app/data
    expose:
      - "8080"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/health"]
      interval: 10s
      timeout: 3s
      retries: 5

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: voiceai-web
    expose:
      - "80"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/health"]
      interval: 10s
      timeout: 3s
      retries: 5
      
  caddy:
    build:
      context: ./reverse-proxy
      dockerfile: Dockerfile
    container_name: voiceai-proxy
    depends_on:
      - backend
      - web
    ports:
      - "${CADDY_HTTP_PORT:-80}:80"
      # Uncomment next line if you enable TLS in Caddyfile
      # - "${CADDY_HTTPS_PORT:-443}:443"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/health"]
      # The proxy /health maps to backend in our Caddyfile; this asserts routing is OK.
      interval: 10s
      timeout: 3s
      retries: 5