version: "3.9"

name: ${COMPOSE_PROJECT_NAME:-voiceai}
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: voiceai-backend
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"
    expose:
      - "8080"
    ports:
      - "8081:8080"     # <--- mappo backend su http://localhost:8081
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/health"]
      interval: 10s
      timeout: 3s
      retries: 5

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: voiceai-web
    expose:
      - "80"
    ports:
      - "8080:80"       # <--- mappo web su http://localhost:8080
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/health"]
      interval: 10s
      timeout: 3s
      retries: 5